(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const x="/wildCoders/assets/wallet-2x-864b430c.jpg",k="/wildCoders/assets/green-2x-dd991c7e.jpg",J="/wildCoders/assets/english-2x-c72afddc.jpg",T="/wildCoders/assets/power-2x-3015a490.jpg",q="/wildCoders/assets/mimino-2x-8b2bf8dc.jpg",M="/wildCoders/assets/vyshyvanka-2x-b502b3d5.jpg",C="/wildCoders/assets/chego-2x-ca6ac779.jpg",N="/wildCoders/assets/energy-2x-311d6b80.jpg",E="/wildCoders/assets/fruitbox-2x-f9988128.jpg",G="/wildCoders/assets/starligth-2x-a84dbdbf.jpg",u=[{id:1,img:"./img/wallet.jpg",img2x:x,description:"React, JavaScript, Node JS, Git",title:"Wallet webservice"},{id:2,img:"./img/green.jpg",img2x:k,description:"React, JavaScript, Node JS, Git",title:"Green harvest online store"},{id:3,img:"./img/english.jpg",img2x:J,description:"React, JavaScript, Node JS, Git",title:"English excellence webservice"},{id:4,img:"./img/power.jpg",img2x:T,description:"React, JavaScript, Node JS, Git",title:"Power pulse webservice"},{id:5,img:"./img/mimino.jpg",img2x:q,description:"React, JavaScript, Node JS, Git",title:"Mimino website"},{id:6,img:"./img/vyshyvanka.jpg",img2x:M,description:"React, JavaScript, Node JS, Git",title:"Vyshyvanka vibes Landing Page"},{id:7,img:"./img/chego.jpg",img2x:C,description:"React, JavaScript, Node JS, Git",title:"Chego jewelry website"},{id:8,img:"./img/energy.jpg",img2x:N,description:"React, JavaScript, Node JS, Git",title:"Energy flow webservice "},{id:9,img:"./img/fruitbox.jpg",img2x:E,description:"React, JavaScript, Node JS, Git",title:"Fruitbox online store"},{id:10,img:"./img/starligth.jpg",img2x:G,description:"React, JavaScript, Node JS, Git",title:"Starlight studio landing page"}],r=document.querySelector(".list-projects"),p=document.querySelector(".button-projects"),a=document.querySelector(".button-hide-projects");a.style.display="none";let c=0;const b=3,S=u.slice(c,c+b);r.insertAdjacentHTML("beforeend",v(S));function v(t){return t.map(({id:s,title:i,description:n,img:e,img2x:o})=>`
    <li class='list-projects-li' data-id='${s}'>
   <img class='list-projects-img' src='${o}' alt='${i}' />
    <p class='list-projects-subtitle'>${n}</p>
    <h3 class='list-projects-title'>${i}</h3>
   <button class='button-projects-visit'>visit
    <svg class="projects-svg" width="24" height="24">
              <use href="./img/icons.svg#icon-gitbrowsre"></use>
            </svg>
   </button>
    </li>
    `).join("")}p.addEventListener("click",()=>{c+=b;const t=u.slice(c,c+b),s=t.some(i=>i.id===u.length);console.log(s),s&&(p.style.display="none",a.style.display="block"),r.insertAdjacentHTML("beforeend",v(t))});a.addEventListener("click",()=>{r.innerHTML="",c=0,r.insertAdjacentHTML("beforeend",v(S)),p.style.display="block",a.style.display="none"});const w=document.querySelector("body"),A=document.querySelector(".mob-menu-btn"),l=document.querySelector(".header-burger"),d=document.querySelector(".mob-menu"),P=document.querySelector(".mob-menu-list");function R(){w.classList.add("noscroll")}function j(){w.classList.remove("noscroll")}P.addEventListener("click",()=>{d.classList.remove("mob-menu-active"),l.classList.toggle("active")});A.addEventListener("click",()=>{l.classList.toggle("active"),l.classList.contains("active")?(d.classList.add("mob-menu-active"),R()):(d.classList.remove("mob-menu-active"),j())});const y=document.querySelector(".switcher-wrapper"),h=document.querySelector(".switcher-menu");let g=!1;const L=`<span class="span-themes"
        ><span class="span-circkle"></span><span class="span-moon"></span
      ></span>`;document.addEventListener("DOMContentLoaded",f);window.addEventListener("resize",f);function f(){window.innerWidth<=768?(y.innerHTML="",h.innerHTML=L):(h.innerHTML="",y.innerHTML=L,d.classList.remove("mob-menu-active"),l.classList.remove("active"),j()),H()}function H(){const t=document.querySelector(".span-themes"),s=document.querySelector(".span-circkle"),i=document.querySelector(".span-moon");t&&s&&i&&(t.addEventListener("click",()=>{t.classList.toggle("span-active"),s.classList.toggle("transform"),i.classList.toggle("transform-moon"),t.classList.contains("span-active")?(document.body.setAttribute("dark",""),g=!0):(document.body.removeAttribute("dark",""),g=!1),localStorage.setItem("blackThemes",g)}),O(t,s,i))}function O(t,s,i){localStorage.getItem("blackThemes")==="true"?(document.body.setAttribute("dark",""),t&&s&&i&&(t.classList.add("span-active"),s.classList.add("transform"),i.classList.add("transform-moon"))):document.body.removeAttribute("dark","")}document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("blackThemes")==="true"?document.body.setAttribute("dark",""):document.body.removeAttribute("dark",""),f()});
//# sourceMappingURL=commonHelpers.js.map
