(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const p=[{id:1,img:"./img/wallet.jpg",img2x:"./img/my-projects/wallet-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Wallet webservice"},{id:2,img:"./img/green.jpg",img2x:"./img/my-projects/green-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Green harvest online store"},{id:3,img:"./img/english.jpg",img2x:"./img/my-projects/english-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"English excellence webservice"},{id:4,img:"./img/power.jpg",img2x:"./img/my-projects/power-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Power pulse webservice"},{id:5,img:"./img/mimino.jpg",img2x:"./img/my-projects/mimino-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Mimino website"},{id:6,img:"./img/vyshyvanka.jpg",img2x:"./img/my-projects/vyshyvanka-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Vyshyvanka vibes Landing Page"},{id:7,img:"./img/chego.jpg",img2x:"./img/my-projects/chego-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Chego jewelry website"},{id:8,img:"./img/energy.jpg",img2x:"./img/my-projects/energy-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Energy flow webservice "},{id:9,img:"./img/fruitbox.jpg",img2x:"./img/my-projects/fruitbox-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Fruitbox online store"},{id:10,img:"./img/starligth.jpg",img2x:"./img/my-projects/starligth-2x.jpg",description:"React, JavaScript, Node JS, Git",title:"Starlight studio landing page"}],n=document.querySelector(".list-projects"),u=document.querySelector(".button-projects"),a=document.querySelector(".button-hide-projects");a.style.display="none";let c=0;const y=3,L=p.slice(c,c+y);n.insertAdjacentHTML("beforeend",v(L));function v(t){return t.map(({id:i,title:s,description:r,img:e,img2x:o})=>`
    <li class='list-projects-li' data-id='${i}'>
   <img class='list-projects-img' src='${o}' alt='${s}' />
    <p class='list-projects-subtitle'>${r}</p>
    <h3 class='list-projects-title'>${s}</h3>
   <button class='button-projects-visit'>visit
    <svg class="projects-svg" width="24" height="24">
              <use href="../img/icons.svg#icon-gitbrowsre"></use>
            </svg>
   </button>
    </li>
    `).join("")}u.addEventListener("click",()=>{c+=y;const t=p.slice(c,c+y),i=t.some(s=>s.id===p.length);console.log(i),i&&(u.style.display="none",a.style.display="block"),n.insertAdjacentHTML("beforeend",v(t))});a.addEventListener("click",()=>{n.innerHTML="",c=0,n.insertAdjacentHTML("beforeend",v(L)),u.style.display="block",a.style.display="none"});const S=document.querySelector("body"),x=document.querySelector(".mob-menu-btn"),l=document.querySelector(".header-burger"),d=document.querySelector(".mob-menu"),k=document.querySelector(".mob-menu-list");function J(){S.classList.add("noscroll")}function w(){S.classList.remove("noscroll")}k.addEventListener("click",()=>{d.classList.remove("mob-menu-active"),l.classList.toggle("active")});x.addEventListener("click",()=>{l.classList.toggle("active"),l.classList.contains("active")?(d.classList.add("mob-menu-active"),J()):(d.classList.remove("mob-menu-active"),w())});const f=document.querySelector(".switcher-wrapper"),j=document.querySelector(".switcher-menu");let g=!1;const h=`<span class="span-themes"
        ><span class="span-circkle"></span><span class="span-moon"></span
      ></span>`;document.addEventListener("DOMContentLoaded",b);window.addEventListener("resize",b);function b(){window.innerWidth<=768?(f.innerHTML="",j.innerHTML=h):(j.innerHTML="",f.innerHTML=h,d.classList.remove("mob-menu-active"),l.classList.remove("active"),w()),T()}function T(){const t=document.querySelector(".span-themes"),i=document.querySelector(".span-circkle"),s=document.querySelector(".span-moon");t&&i&&s&&(t.addEventListener("click",()=>{t.classList.toggle("span-active"),i.classList.toggle("transform"),s.classList.toggle("transform-moon"),t.classList.contains("span-active")?(document.body.setAttribute("dark",""),g=!0):(document.body.removeAttribute("dark",""),g=!1),localStorage.setItem("blackThemes",g)}),q(t,i,s))}function q(t,i,s){localStorage.getItem("blackThemes")==="true"?(document.body.setAttribute("dark",""),t&&i&&s&&(t.classList.add("span-active"),i.classList.add("transform"),s.classList.add("transform-moon"))):document.body.removeAttribute("dark","")}document.addEventListener("DOMContentLoaded",()=>{localStorage.getItem("blackThemes")==="true"?document.body.setAttribute("dark",""):document.body.removeAttribute("dark",""),b()});
//# sourceMappingURL=commonHelpers.js.map
